repository: naoigcat/presentations
url: https://naoigcat.github.io/presentations
title: Presentations
author: naoigcat
github_username: naoigcat
description: >-
  Anyone who has never made a mistake has never tried anything new.
source: ./docs
destination: ./_site
theme: minima
google_analytics: UA-158986608-1
