repository: naoigcat/presentations
url: https://naoigcat.github.io/presentations
title: Presentations
author: naoigcat
github_username: naoigcat
description: >-
  Don' t be afraid of making mistakes.
exclude:
  - .gitignore
theme: minima
google_analytics: UA-158986608-1
